// SPDX-License-Identifier: MIT OR Apache-2.0
// SPDX-FileCopyrightText: 2025-2026 ObzenFlow Contributors
// https://obzenflow.dev

//! Adapter-owned observer composition (FLOWIP-115f onion conformance).
//!
//! This module folds the resolved per-surface observer list for a stage into a
//! single composed port, exactly as `Per*PolicyBoundary` folds a control-policy
//! stack into one boundary. The runtime then holds one neutral port per surface
//! (`StageObserverBundle`) and calls it once. The list, the determinism gate,
//! and report merging live here, so the runtime never iterates an observer list
//! or evaluates observer determinism itself.

use std::sync::Arc;

use obzenflow_core::ChainEvent;
use obzenflow_runtime::{
    EffectObserver, EffectObserverContext, HandlerObserver, HandlerObserverContext,
    IngressObserver, IngressObserverContext, JoinObserver, JoinObserverContext,
    ObserverCommitResult, ObserverReport, OutputCommitObserver, OutputCommitObserverContext,
    SinkDeliveryObserver, SinkDeliveryObserverContext, SourcePollObserver,
    SourcePollObserverContext, StageLifecycleObserver, StageLifecycleObserverContext,
    StageObserverBundle, StatefulObserver, StatefulObserverContext,
};

use crate::middleware::{MiddlewareSurfaceAttachment, MiddlewareSurfaceKind};

/// Maps each observer-capable surface to its runtime observer port. One
/// implementor per surface, generated by [`observer_surfaces!`], so a surface
/// cannot be observer-capable without a port and cannot be wired without being
/// capable.
///
/// Lives in adapters because it maps carrier surfaces (adapter-owned) to runtime
/// ports (runtime-owned); that mapping is the adapter's role. Runtime keeps its
/// port traits, contexts, and the plain `StageObserverBundle`, and never learns
/// about surfaces or attachments. No context type lives here: contexts are built
/// and consumed by the runtime dispatch helpers, which are runtime-owned.
pub(crate) trait ObserverSurface {
    /// The runtime-owned observer port this surface exposes.
    type Port: ?Sized + Send + Sync + 'static;

    /// The carrier surface-kind discriminant this surface answers to.
    const KIND: MiddlewareSurfaceKind;

    /// Fold a non-empty resolved observer list into the one composed port.
    fn compose(list: Vec<Arc<Self::Port>>) -> Arc<Self::Port>;
}

/// Generates, from one row per observer-capable surface, the [`ObserverSurface`]
/// markers and impls, the [`StageObserverSet`] builder (fields, `push_attachment`,
/// `extend`, `build`), and the [`OBSERVER_SURFACE_KINDS`] set the carrier gate
/// consults. Adding a surface is one row; the compiler then requires its port
/// (runtime), its attachment variant (carrier), its bundle field (runtime), and
/// its chain type to exist before the row compiles.
macro_rules! observer_surfaces {
    (
        control_attachments: [ $($control:ident),+ $(,)? ],
        surfaces: [ $(
            $marker:ident {
                kind: $kind:ident,
                port: $port:ident,
                attach: $attach:ident,
                field: $field:ident,
                chain: $chain:ident $(,)?
            }
        ),+ $(,)? ]
    ) => {
        $(
            pub(crate) struct $marker;

            impl ObserverSurface for $marker {
                type Port = dyn $port;
                const KIND: MiddlewareSurfaceKind = MiddlewareSurfaceKind::$kind;
                fn compose(list: Vec<Arc<Self::Port>>) -> Arc<Self::Port> {
                    Arc::new($chain(list))
                }
            }
        )+

        /// Accumulates the resolved observer attachments for one stage, then
        /// folds each surface's list into one composed port via
        /// [`StageObserverSet::build`].
        #[derive(Default)]
        pub struct StageObserverSet {
            $( pub(crate) $field: Vec<Arc<dyn $port>>, )+
        }

        impl StageObserverSet {
            /// Route one materialized observer attachment onto its surface list.
            /// Control attachments are rejected. The match is exhaustive (no
            /// wildcard), so a new `MiddlewareSurfaceAttachment` variant forces a
            /// decision here at compile time rather than being silently dropped.
            pub fn push_attachment(
                &mut self,
                attachment: MiddlewareSurfaceAttachment,
            ) -> Result<(), String> {
                match attachment {
                    $(
                        MiddlewareSurfaceAttachment::$attach(observer) => self.$field.push(observer),
                    )+
                    $( MiddlewareSurfaceAttachment::$control(_) )|+ => {
                        return Err(
                            "middleware materialized a control attachment while planning observers"
                                .into(),
                        )
                    }
                }
                Ok(())
            }

            /// Merge another set's lists into this one, preserving declared order.
            pub fn extend(&mut self, other: StageObserverSet) {
                $( self.$field.extend(other.$field); )+
            }

            /// Fold each surface's list into one composed runtime port. An empty
            /// list yields `None` so the runtime skips that surface entirely. The
            /// struct literal ties the runtime bundle shape to this table: a new
            /// bundle field will not compile until it has a row here.
            pub fn build(self) -> StageObserverBundle {
                StageObserverBundle {
                    $(
                        $field: if self.$field.is_empty() {
                            None
                        } else {
                            Some(<$marker as ObserverSurface>::compose(self.$field))
                        },
                    )+
                }
            }
        }

        /// The observer-capable surface kinds, derived from the same table that
        /// wires their ports. The carrier gate consults this, so a surface is
        /// observer-capable if and only if it has a port here.
        pub(crate) const OBSERVER_SURFACE_KINDS: &[MiddlewareSurfaceKind] =
            &[ $( <$marker as ObserverSurface>::KIND ),+ ];
    };
}

observer_surfaces! {
    control_attachments: [SourcePoll, Effect, SinkDelivery, Ingress],
    surfaces: [
        HandlerObserverSurface {
            kind: Handler, port: HandlerObserver, attach: HandlerObserver,
            field: handler, chain: HandlerObserverChain,
        },
        StatefulObserverSurface {
            kind: Stateful, port: StatefulObserver, attach: StatefulObserver,
            field: stateful, chain: StatefulObserverChain,
        },
        JoinObserverSurface {
            kind: Join, port: JoinObserver, attach: JoinObserver,
            field: join, chain: JoinObserverChain,
        },
        SourcePollObserverSurface {
            kind: SourcePoll, port: SourcePollObserver, attach: SourcePollObserver,
            field: source_poll, chain: SourcePollObserverChain,
        },
        EffectObserverSurface {
            kind: Effect, port: EffectObserver, attach: EffectObserver,
            field: effect, chain: EffectObserverChain,
        },
        SinkDeliveryObserverSurface {
            kind: SinkDelivery, port: SinkDeliveryObserver, attach: SinkDeliveryObserver,
            field: sink_delivery, chain: SinkDeliveryObserverChain,
        },
        IngressObserverSurface {
            kind: Ingress, port: IngressObserver, attach: IngressObserver,
            field: ingress, chain: IngressObserverChain,
        },
        OutputCommitObserverSurface {
            kind: OutputCommit, port: OutputCommitObserver, attach: OutputCommitObserver,
            field: output_commit, chain: OutputCommitObserverChain,
        },
        StageLifecycleObserverSurface {
            kind: StageLifecycle, port: StageLifecycleObserver, attach: StageLifecycleObserver,
            field: stage_lifecycle, chain: StageLifecycleObserverChain,
        },
    ]
}

const CHAIN_LABEL: &str = "observer-chain";

struct HandlerObserverChain(Vec<Arc<dyn HandlerObserver>>);

impl HandlerObserver for HandlerObserverChain {
    fn label(&self) -> &'static str {
        CHAIN_LABEL
    }

    fn before_handle(&self, ctx: &HandlerObserverContext<'_>) -> ObserverReport {
        let mut merged = ObserverReport::empty();
        for observer in &self.0 {
            if observer.determinism().should_run(ctx.scope) {
                merged
                    .diagnostics
                    .extend(observer.before_handle(ctx).diagnostics);
            }
        }
        merged
    }

    fn after_handle(
        &self,
        ctx: &HandlerObserverContext<'_>,
        outputs: &mut [ChainEvent],
    ) -> ObserverReport {
        let mut merged = ObserverReport::empty();
        for observer in &self.0 {
            if observer.determinism().should_run(ctx.scope) {
                merged
                    .diagnostics
                    .extend(observer.after_handle(ctx, outputs).diagnostics);
            }
        }
        merged
    }
}

struct StatefulObserverChain(Vec<Arc<dyn StatefulObserver>>);

impl StatefulObserver for StatefulObserverChain {
    fn label(&self) -> &'static str {
        CHAIN_LABEL
    }

    fn before_state_accumulate(&self, ctx: &StatefulObserverContext<'_>) -> ObserverReport {
        let mut merged = ObserverReport::empty();
        for observer in &self.0 {
            if observer.determinism().should_run(ctx.scope) {
                merged
                    .diagnostics
                    .extend(observer.before_state_accumulate(ctx).diagnostics);
            }
        }
        merged
    }

    fn after_state_accumulate(&self, ctx: &StatefulObserverContext<'_>) -> ObserverReport {
        let mut merged = ObserverReport::empty();
        for observer in &self.0 {
            if observer.determinism().should_run(ctx.scope) {
                merged
                    .diagnostics
                    .extend(observer.after_state_accumulate(ctx).diagnostics);
            }
        }
        merged
    }

    fn after_state_emit(
        &self,
        ctx: &StatefulObserverContext<'_>,
        outputs: &mut [ChainEvent],
    ) -> ObserverReport {
        let mut merged = ObserverReport::empty();
        for observer in &self.0 {
            if observer.determinism().should_run(ctx.scope) {
                merged
                    .diagnostics
                    .extend(observer.after_state_emit(ctx, outputs).diagnostics);
            }
        }
        merged
    }
}

struct JoinObserverChain(Vec<Arc<dyn JoinObserver>>);

impl JoinObserver for JoinObserverChain {
    fn label(&self) -> &'static str {
        CHAIN_LABEL
    }

    fn before_join_input(&self, ctx: &JoinObserverContext<'_>) -> ObserverReport {
        let mut merged = ObserverReport::empty();
        for observer in &self.0 {
            if observer.determinism().should_run(ctx.scope) {
                merged
                    .diagnostics
                    .extend(observer.before_join_input(ctx).diagnostics);
            }
        }
        merged
    }

    fn after_join_output(
        &self,
        ctx: &JoinObserverContext<'_>,
        outputs: &mut [ChainEvent],
    ) -> ObserverReport {
        let mut merged = ObserverReport::empty();
        for observer in &self.0 {
            if observer.determinism().should_run(ctx.scope) {
                merged
                    .diagnostics
                    .extend(observer.after_join_output(ctx, outputs).diagnostics);
            }
        }
        merged
    }
}

struct SourcePollObserverChain(Vec<Arc<dyn SourcePollObserver>>);

impl SourcePollObserver for SourcePollObserverChain {
    fn label(&self) -> &'static str {
        CHAIN_LABEL
    }

    fn after_source_poll(
        &self,
        ctx: &SourcePollObserverContext<'_>,
        outputs: &mut [ChainEvent],
    ) -> ObserverReport {
        let mut merged = ObserverReport::empty();
        for observer in &self.0 {
            if observer.determinism().should_run(ctx.scope) {
                merged
                    .diagnostics
                    .extend(observer.after_source_poll(ctx, outputs).diagnostics);
            }
        }
        merged
    }
}

struct EffectObserverChain(Vec<Arc<dyn EffectObserver>>);

impl EffectObserver for EffectObserverChain {
    fn label(&self) -> &'static str {
        CHAIN_LABEL
    }

    fn after_effect(&self, ctx: &EffectObserverContext<'_>) -> ObserverReport {
        let mut merged = ObserverReport::empty();
        for observer in &self.0 {
            if observer.determinism().should_run(ctx.scope) {
                merged
                    .diagnostics
                    .extend(observer.after_effect(ctx).diagnostics);
            }
        }
        merged
    }
}

struct SinkDeliveryObserverChain(Vec<Arc<dyn SinkDeliveryObserver>>);

impl SinkDeliveryObserver for SinkDeliveryObserverChain {
    fn label(&self) -> &'static str {
        CHAIN_LABEL
    }

    fn after_sink_delivery(&self, ctx: &SinkDeliveryObserverContext<'_>) -> ObserverReport {
        let mut merged = ObserverReport::empty();
        for observer in &self.0 {
            if observer.determinism().should_run(ctx.scope) {
                merged
                    .diagnostics
                    .extend(observer.after_sink_delivery(ctx).diagnostics);
            }
        }
        merged
    }
}

struct IngressObserverChain(Vec<Arc<dyn IngressObserver>>);

impl IngressObserver for IngressObserverChain {
    fn label(&self) -> &'static str {
        CHAIN_LABEL
    }

    fn after_ingress(&self, ctx: &IngressObserverContext<'_>) -> ObserverReport {
        // Ingress observation runs at the listener boundary, which replay never
        // enters, so there is no handler-shell determinism gate here.
        let mut merged = ObserverReport::empty();
        for observer in &self.0 {
            merged
                .diagnostics
                .extend(observer.after_ingress(ctx).diagnostics);
        }
        merged
    }
}

struct OutputCommitObserverChain(Vec<Arc<dyn OutputCommitObserver>>);

impl OutputCommitObserver for OutputCommitObserverChain {
    fn label(&self) -> &'static str {
        CHAIN_LABEL
    }

    fn before_output_commit(
        &self,
        ctx: &OutputCommitObserverContext<'_>,
        event: &mut ChainEvent,
    ) -> ObserverCommitResult {
        let mut merged = ObserverReport::empty();
        for observer in &self.0 {
            if observer.determinism().should_run(ctx.scope) {
                let report = observer.before_output_commit(ctx, event)?;
                merged.diagnostics.extend(report.diagnostics);
            }
        }
        Ok(merged)
    }
}

struct StageLifecycleObserverChain(Vec<Arc<dyn StageLifecycleObserver>>);

impl StageLifecycleObserver for StageLifecycleObserverChain {
    fn label(&self) -> &'static str {
        CHAIN_LABEL
    }

    fn on_stage_lifecycle(&self, ctx: &StageLifecycleObserverContext<'_>) -> ObserverReport {
        let mut merged = ObserverReport::empty();
        for observer in &self.0 {
            if observer.determinism().should_run(ctx.scope) {
                merged
                    .diagnostics
                    .extend(observer.on_stage_lifecycle(ctx).diagnostics);
            }
        }
        merged
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use obzenflow_core::event::context::{FlowContext, MiddlewareExecutionScope, StageType};
    use obzenflow_core::event::ChainEventFactory;
    use obzenflow_core::{StageId, WriterId};
    use obzenflow_runtime::ObserverDeterminism;
    use std::sync::atomic::{AtomicUsize, Ordering};

    /// A handler observer that counts its invocations, so a test can prove the
    /// composed port gated it (or not) without constructing diagnostic events.
    struct CountingHandlerObserver {
        calls: AtomicUsize,
        determinism: ObserverDeterminism,
    }

    impl CountingHandlerObserver {
        fn new(determinism: ObserverDeterminism) -> Arc<Self> {
            Arc::new(Self {
                calls: AtomicUsize::new(0),
                determinism,
            })
        }

        fn calls(&self) -> usize {
            self.calls.load(Ordering::SeqCst)
        }
    }

    impl HandlerObserver for CountingHandlerObserver {
        fn label(&self) -> &'static str {
            "counting"
        }

        fn determinism(&self) -> ObserverDeterminism {
            self.determinism
        }

        fn before_handle(&self, _ctx: &HandlerObserverContext<'_>) -> ObserverReport {
            self.calls.fetch_add(1, Ordering::SeqCst);
            ObserverReport::empty()
        }
    }

    fn invoke(port: &Arc<dyn HandlerObserver>, scope: MiddlewareExecutionScope) {
        let flow_context = FlowContext {
            flow_name: "f".to_string(),
            flow_id: "f1".to_string(),
            stage_name: "s".to_string(),
            stage_id: StageId::new(),
            stage_type: StageType::Transform,
        };
        let event = ChainEventFactory::data_event(
            WriterId::from(StageId::new()),
            "test.event",
            serde_json::json!({}),
        );
        let ctx = HandlerObserverContext {
            stage_id: flow_context.stage_id,
            stage_name: &flow_context.stage_name,
            flow_context: &flow_context,
            scope,
            input: &event,
            stage_input_position: Some(1),
        };
        port.before_handle(&ctx);
    }

    #[test]
    fn live_only_observer_is_suppressed_under_replay_by_the_composite() {
        let observer = CountingHandlerObserver::new(ObserverDeterminism::LiveOnly);
        let mut set = StageObserverSet::default();
        set.handler.push(observer.clone());
        let port = set.build().handler.expect("handler port composed");

        invoke(&port, MiddlewareExecutionScope::LiveHandler);
        assert_eq!(observer.calls(), 1, "live-only observer runs live");

        invoke(&port, MiddlewareExecutionScope::StrictReplayHandler);
        invoke(&port, MiddlewareExecutionScope::ResumeHandler);
        assert_eq!(
            observer.calls(),
            1,
            "live-only observer is suppressed under strict replay and resume"
        );
    }

    #[test]
    fn deterministic_observer_runs_under_replay() {
        let observer = CountingHandlerObserver::new(ObserverDeterminism::Deterministic);
        let mut set = StageObserverSet::default();
        set.handler.push(observer.clone());
        let port = set.build().handler.expect("handler port composed");

        invoke(&port, MiddlewareExecutionScope::StrictReplayHandler);
        assert_eq!(
            observer.calls(),
            1,
            "deterministic observer runs under replay"
        );
    }

    #[test]
    fn composite_invokes_every_child() {
        let a = CountingHandlerObserver::new(ObserverDeterminism::Deterministic);
        let b = CountingHandlerObserver::new(ObserverDeterminism::Deterministic);
        let mut set = StageObserverSet::default();
        set.handler.push(a.clone());
        set.handler.push(b.clone());
        let port = set.build().handler.expect("handler port composed");

        invoke(&port, MiddlewareExecutionScope::LiveHandler);
        assert_eq!(a.calls(), 1);
        assert_eq!(b.calls(), 1);
    }

    #[test]
    fn empty_surface_composes_to_none() {
        let bundle = StageObserverSet::default().build();
        assert!(bundle.handler.is_none());
        assert!(bundle.is_empty());
    }

    #[test]
    fn observer_surface_kinds_cover_every_surface() {
        // Every surface kind has an observer port, so the carrier gate derived
        // from this set is correct: observer-capable iff a port exists. A surface
        // kind added without a wiring row is absent here and the gate rejects
        // observer attachment, which is the fail-closed behaviour we want.
        let all = [
            MiddlewareSurfaceKind::SourcePoll,
            MiddlewareSurfaceKind::Effect,
            MiddlewareSurfaceKind::SinkDelivery,
            MiddlewareSurfaceKind::Ingress,
            MiddlewareSurfaceKind::Handler,
            MiddlewareSurfaceKind::Stateful,
            MiddlewareSurfaceKind::Join,
            MiddlewareSurfaceKind::OutputCommit,
            MiddlewareSurfaceKind::StageLifecycle,
        ];
        for kind in all {
            assert!(
                OBSERVER_SURFACE_KINDS.contains(&kind),
                "{kind:?} has no observer wiring row"
            );
        }
        assert_eq!(OBSERVER_SURFACE_KINDS.len(), all.len());
    }

    #[test]
    fn push_attachment_routes_observer_to_its_surface() {
        let observer = CountingHandlerObserver::new(ObserverDeterminism::Deterministic);
        let mut set = StageObserverSet::default();
        set.push_attachment(MiddlewareSurfaceAttachment::HandlerObserver(observer))
            .expect("a handler observer routes to the handler surface");
        assert_eq!(set.handler.len(), 1);
        assert!(set.stateful.is_empty());
    }
}
